name: .NET

on: [ push, pull_request ]

env:
  DOTNET_SDK_VERSION: 5.0.x

jobs:
  build-generic:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with .NET Core
        run: dotnet publish -c Release -f net5.0 -o out/${{ github.event.repository.name }}-generic

      - name: Upload generic artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-generic
          path: out/${{ github.event.repository.name }}-generic

  build-generic-netf:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with .NET Framework
        run: dotnet publish -c Release -f net48 -o out/${{ github.event.repository.name }}-generic-netf

      - name: Upload generic-netf artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-generic-netf
          path: out/${{ github.event.repository.name }}-generic-netf

  release:
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
    needs: [build-generic-netf, build-generic]
    runs-on: ubuntu-latest

    steps:
      - name: Download generic artifacts
        uses: actions/download-artifact@v2.1.0
        with:
          name: ${{ github.event.repository.name }}-generic
          path: out/${{ github.event.repository.name }}-generic

      - name: Download generic-netf artifacts
        uses: actions/download-artifact@v2.1.0
        with:
          name: ${{ github.event.repository.name }}-generic-netf
          path: out/${{ github.event.repository.name }}-generic-netf

      - name: Archive generic release
        uses: thedoctor0/zip-release@master
        with:
          directory: out
          path: ${{ github.event.repository.name }}-generic
          type: 'zip'
          filename: 'generic.zip'
          exclusions: '*.json'

      - name: Archive generic-netf release
        uses: thedoctor0/zip-release@master
        with:
          directory: out
          path: ${{ github.event.repository.name }}-generic-netf
          type: 'zip'
          filename: 'generic-netf.zip'
          exclusions: '*.json'

      - name: Create GitHub release
        id: github_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.event.repository.name }} V${{ github.ref }}

      - name: Upload generic artifacts to GitHub release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.github_release.outputs.upload_url }}
          asset_path: out/generic.zip
          asset_name: generic.zip
          asset_content_type: application/zip

      - name: Upload generic-netf artifacts to GitHub release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.github_release.outputs.upload_url }}
          asset_path: out/generic-netf.zip
          asset_name: generic-netf.zip
          asset_content_type: application/zip